language: d
sudo: false

matrix:
  include:
    - d: dmd-2.070.2
    - d: dmd-2.071.2
    - d: dmd-2.072.0
    - d: dmd-2.072.2
    - d: dmd-2.073.0
    - d: dmd-beta
    - d: ldc-1.0.0
    - d: ldc-1.1.0-beta6

script:
  - dub test --compiler=${DC}

notifications:
  email: false
